services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Asmitta\ToastBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Asmitta\ToastBundle\Twig\ToastExtension:
        tags: ['twig.extension']